# Generated by Django 5.0.2 on 2024-02-28 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_slots_available_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecenter',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='capacity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
