# Generated by Django 5.0.2 on 2024-02-28 04:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_vaccinecenter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='capacity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
