# Generated by Django 5.0.2 on 2024-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_remove_booking_date_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecenter',
            name='dosage',
        ),
        migrations.AddField(
            model_name='booking',
            name='dosage',
            field=models.IntegerField(default=0),
        ),
    ]
