# Generated by Django 5.0.2 on 2024-02-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_remove_vaccinecenter_dosage_booking_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dosage',
            field=models.IntegerField(default=1),
        ),
    ]
